### ISSUE TITLE
What is the result of `getFactorTraditional` means?

### ISSUE THREAD

**Issue by reza-ghazi** [mit1280/primelibpy#3]
```py
p.getFactorTraditional(1232561)
```
```bash
112051
```
What is the meaning of the above result?

**The prime factors of `1232561` are `[1, 11, 89, 1259]`.**

**Comment by mit1280** [comment]
Hi Ghazi,
Sorry for the late response. I created "getFactorTraditional", "getFactorFermatTheorem", "getFactorPollardRho" functions for Semi-prime. Most of the security algorithm uses Semi-prime as Key so these functions return one of the Prime. Currently "getFactorTraditional" returned one of the Factors of a given number(112051 = 89*1259). I'll change the Library so it'll avoid confusion.
