### ISSUE TITLE
Function checkGaussianPrime fails

### ISSUE THREAD

**Issue by naomimk46** [mit1280/primelibpy#4]
A Gaussian Prime, up to associates, are of the form:

1. 1+i
2.  $\alpha = a +bi$  and $\bar{\alpha}=a-bi$, where $\alpha\bar{\alpha}$ is a prime integer $q$ of the form $4k+1$ 
3.  $p$, where $p$ is a prime integer of the form $4k+3$

When I try to use checkGaussianPrime for the third form it returns the string 'p is not a gaussian prime' what is incorrect.

**Comment by mit1280** [comment]
@naomimk46 - Thanks for pointing this out!

A Gaussian prime is divided into two parts:
Consider complex number: $\alpha = a +bi$
1. Either imaginary or real number is zero. 
if a = 0, |b| must be in for of 4n+1 or $|b| ≡ 3 (mod 4)$ .
if b = 0, |a| must be in for of 4n+1 or $|a| ≡ 3 (mod 4)$ .

2. Both numbers are non-zero. 
if a&b are non-zero, $a^2+b^2$
Current code is only able to handle 2nd condition. I will make a fix for first point.

I made quick update here: https://colab.research.google.com/drive/1y5t3mTuuLK86z3o5nsH3VMUNu25E5m9t?usp=sharing
I will update Repo soon.
